version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/travel_web_dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run start:dev

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=travel_web_dev

volumes:
  mongo_data:
